package com.kodexis.core.learning.model;

import java.util.ArrayList;
import java.util.List;

public class QuizQuestion {
    public enum QuestionType {
        MCQ,
        SHORT_ANSWER,
        NUMERICAL
    }

    private String id;
    private QuestionType type;
    private String topicId;
    private String topicName;
    private String conceptId;
    private String conceptName;
    private String difficulty; // "EASY", "MEDIUM", "HARD"
    private String questionText;
    private List<String> options = new ArrayList<>(); // For MCQ
    private String correctAnswer;
    private Double numericalTolerance; // e.g. ±0.05 for numerical questions
    private String numericalUnit; // e.g. "ms", "MB", "hops"
    private String detailedExplanation;
    private String sourceLocation; // e.g. "[Operating Systems Slide 24]"
    private String sourceUnitId;
    private String misconceptionKey; // Identifies common misconception targeted by wrong answers
    private boolean crossModelVerified; // Verified question correctness
    private String verificationProof; // Proof generated by verification pass
    private String questionHash; // For avoiding repeated questions across assessments

    public QuizQuestion() {}

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public QuestionType getType() { return type; }
    public void setType(QuestionType type) { this.type = type; }

    public String getTopicId() { return topicId; }
    public void setTopicId(String topicId) { this.topicId = topicId; }

    public String getTopicName() { return topicName; }
    public void setTopicName(String topicName) { this.topicName = topicName; }

    public String getConceptId() { return conceptId; }
    public void setConceptId(String conceptId) { this.conceptId = conceptId; }

    public String getConceptName() { return conceptName; }
    public void setConceptName(String conceptName) { this.conceptName = conceptName; }

    public String getDifficulty() { return difficulty; }
    public void setDifficulty(String difficulty) { this.difficulty = difficulty; }

    public String getQuestionText() { return questionText; }
    public void setQuestionText(String questionText) { this.questionText = questionText; }

    public List<String> getOptions() { return options; }
    public void setOptions(List<String> options) { this.options = options; }

    public String getCorrectAnswer() { return correctAnswer; }
    public void setCorrectAnswer(String correctAnswer) { this.correctAnswer = correctAnswer; }

    public Double getNumericalTolerance() { return numericalTolerance; }
    public void setNumericalTolerance(Double numericalTolerance) { this.numericalTolerance = numericalTolerance; }

    public String getNumericalUnit() { return numericalUnit; }
    public void setNumericalUnit(String numericalUnit) { this.numericalUnit = numericalUnit; }

    public String getDetailedExplanation() { return detailedExplanation; }
    public void setDetailedExplanation(String detailedExplanation) { this.detailedExplanation = detailedExplanation; }

    public String getSourceLocation() { return sourceLocation; }
    public void setSourceLocation(String sourceLocation) { this.sourceLocation = sourceLocation; }

    public String getSourceUnitId() { return sourceUnitId; }
    public void setSourceUnitId(String sourceUnitId) { this.sourceUnitId = sourceUnitId; }

    public String getMisconceptionKey() { return misconceptionKey; }
    public void setMisconceptionKey(String misconceptionKey) { this.misconceptionKey = misconceptionKey; }

    public boolean isCrossModelVerified() { return crossModelVerified; }
    public void setCrossModelVerified(boolean crossModelVerified) { this.crossModelVerified = crossModelVerified; }

    public String getVerificationProof() { return verificationProof; }
    public void setVerificationProof(String verificationProof) { this.verificationProof = verificationProof; }

    public String getQuestionHash() { return questionHash; }
    public void setQuestionHash(String questionHash) { this.questionHash = questionHash; }
}
